### ISSUE TITLE
Sky graphic is visible when expanding/collapsing

### ISSUE THREAD

**Issue by SalvatoreT** [romainguy/sample-wake-me-up#1]
If you have a clocks that are close enough together, you can see the sky rendering when you expand and collapse the view. I reproduced this on a physical Galaxy S8 (API 28) and a Pixel 5 (API 31) emulator.

![sky-is-showing](https://user-images.githubusercontent.com/1223008/137397404-357e6d3e-2f80-4c80-a3fe-548131252580.gif)

**Comment by romainguy** [comment]
@SalvatoreT You could try to upgrade to compose 1.1.0-alphaX and see if it fixes it.
